apiVersion: v1
kind: Namespace
metadata:
  name: voting-app-with-kubernetes

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deployment
  namespace: voting-app-with-kubernetes
  labels:
    name: voting-deployment
    app: vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-deployment
      app: vote-app
  template:
    metadata:
      labels:
        name: voting-deployment
        app: vote-app
    spec:
      containers:
      - name: vote
        image: rezamuhammadi/kube-voting:vote
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: voting-app-nodeport-service
  namespace: voting-app-with-kubernetes
  labels:
    name: voting-app-nodeport-service
    app: vote-app
spec:
  type: NodePort
  selector:
    name: voting-deployment
    app: vote-app
  ports:
  - targetPort: 80
    port: 6000
    nodePort: 30600

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: voting-app-with-kubernetes
  labels:
    name: result
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result
      app: result
  template:
    metadata:
      labels:
        name: result
        app: result
    spec:
      containers:
      - name: result
        image: rezamuhammadi/kube-voting:result
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: voting-app-with-kubernetes
  labels:
    name: result
    app: result
spec:
  type: NodePort
  selector:
    name: result
    app: result
  ports:
  - targetPort: 80
    port: 6001
    nodePort: 30601
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: voting-app-with-kubernetes
  labels:
    name: redis
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
      app: redis
  template:
    metadata:
      labels:
        name: redis
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: voting-app-with-kubernetes
  labels:
    app: redis
    name: redis
spec:
  selector:
    name: redis
    app: redis
  type: ClusterIP
  ports:
  - targetPort: 6379
    port: 6379

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: voting-app-with-kubernetes
  labels:
    name: db
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db
      app: db
  template:
    metadata:
      labels:
        name: db
        app: db
    spec:
      containers:
      - name: db
        image: postgres:9.4
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres"

---

apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: voting-app-with-kubernetes
  labels:
    name: db
    app: db
spec:
  selector:
    name: db
    app: db
  type: ClusterIP
  ports:
  - targetPort: 5432
    port: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: voting-app-with-kubernetes
  labels:
    name: worker-deployment
    app: vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-deployment
      app: vote-app
  template:
    metadata:
      labels:
        name: worker-deployment
        app: vote-app
    spec:
      containers:
      - name: worker
        image: rezamuhammadi/kube-voting:worker
